#!/bin/bash
source /home/TUE/TUE_20185358/miniconda3/etc/profile.d/conda.sh
source activate condaenv
i=1
n='ResNet'
echo python3          main100_run.py --net=$n --epochs=150 --idx=$i
python3 pytorch-cifar/main100_run.py --net=$n --epochs=150 --idx=$i
python3 pytorch-cifar/main100_run.py --resume --epochs=75 --lr=0.01 --net=$n --idx=$i
python3 pytorch-cifar/main100_run.py --resume --epochs=75 --lr=0.001 --net=$n --idx=$i

#echo python3             attack_softmax.py --net=$n --km $k --samples 500 --filename='ckpt'$r$n'km_'$i
#python3 one-pixel-attack/attack_softmax.py --net=$n --km=$k --samples 500 --filename='ckpt'$r$n'km_'$i

echo python3 pytorch-cifar/main100_run.py --net=$n --epochs=20 --idx=$i
python3 pytorch-cifar/main100_run.py --net=$n --epochs=20 --idx=$i
echo cp checkpoint/ckpt100$n'_'$i'.t7' checkpoint/ckpt100GA$n'_'$i'.t7'
cp checkpoint/ckpt100$n'_'$i'.t7' checkpoint/ckpt100GA$n'_'$i'.t7'
echo python3 pytorch-cifar/main100_gauss.py --gamma=1 --initCentroids=1 --resume --lr=0.1 --epochs=100 --net=$n --idx=$i
python3 pytorch-cifar/main100_gauss.py --gamma=1 --initCentroids=1 --resume --lr=0.1 --epochs=100 --net=$n --idx=$i
python3 pytorch-cifar/main100_gauss.py --gamma=1 --resume --epochs=75 --lr=0.01 --net=$n --idx=$i
python3 pytorch-cifar/main100_gauss.py --gamma=1 --resume --epochs=75 --lr=0.001 --net=$n --idx=$i

#echo python3             attack.py --net=$n --samples 100 --filename='ckptGA'$n'_'$i
#python3 one-pixel-attack/attack.py --net=$n --samples 100 --filename='ckptGA'$n'_'$i

source deactivate
